### ISSUE TITLE
[Feature Request] controller options and dropping items

### ISSUE THREAD

**Issue by sunnyxu715** [ConnorMulqueen/Geesenado#100]
I'm not sure about you guys, but for me it is really counter intuitive to play a 2-D game that requires a left click to fire. Also, I think it is better if you can drop some of the items. If one picks up the same item 5 times in a row, he would stuck with that item.

**Comment by jaredgav** [comment]
The concept behind left click fire is due to the fact the character rotates and looks at the mouse position. Since your hand is already part of controlling the character we assumed it makes sense to then click with your mouse hand and move with WASD for the left hand. If you would like a space bar option to fire we can add it, but remember you only have two hands. :)

The item drop is soon to come! Thank you!
